Repository Frc5572/FRC2022, pull requests merged in 2022-02, with the labels that each got.

#49 Add pathweaver fix bugs
  pathweaver/fields/2022-rapidreact/2022-field.png
  pathweaver/fields/2022-rapidreact/2022-field_grid.png
  pathweaver/fields/2022-rapidreact/2022-rapidreact.json
  pathweaver/fields/2022-rapidreact/notes.md
  pathweaver/fields/INSTALL.md
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Climber.java
Labels: bug, enhancement

#51 Add Path Planner
  .vscode/settings.json
  src/main/deploy/pathplanner/Get 3 Balls.path
  src/main/deploy/pathplanner/Rusinski's.path
  src/main/deploy/pathplanner/generatedJSON/Get 3 Balls.wpilib.json
  src/main/deploy/pathplanner/generatedJSON/Rusinski's.wpilib.json
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/TestAuto.java
  src/main/java/frc/robot/subsystems/Magazine.java
  src/main/java/frc/robot/subsystems/Shooter.java
  vendordeps/PathplannerLib.json
Labels: bug, enhancement, Autonomous

#57 Update WPIlib
  build.gradle
Labels: enhancement

#79 Create Auto Parent Class
  src/main/java/frc/robot/autos/LimelightAuto.java
  src/main/java/frc/robot/autos/TestAuto.java
  src/main/java/frc/robot/autos/TestNoZeroGyroAuto.java
  src/main/java/frc/robot/modules/AutoBase.java
Labels: Autonomous

#84 Merge Auto P1_2B/P3_2B into Main
  checks.xml
  src/main/deploy/pathplanner/P3_2B.path
  src/main/deploy/pathplanner/P_2B.path
  src/main/deploy/pathplanner/generatedJSON/P0.wpilib.json
  src/main/deploy/pathplanner/generatedJSON/P3_2B.wpilib.json
  src/main/deploy/pathplanner/generatedJSON/P_2B.wpilib.json
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/modules/AutoBase.java
  src/main/java/frc/robot/modules/Vision.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: Autonomous
