Repository Frc5572/FRC2022, pull requests merged in 2022-03, with the labels that each got.

#103 Hopper Down.
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Magazine.java
Labels: enhancement, priority: medium

#112 Variable Setpoint based on Distance from Target
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/MagazineRPM.java
  src/main/java/frc/robot/commands/ShooterRPM.java
  src/main/java/frc/robot/subsystems/Hood.java
  src/main/java/frc/robot/subsystems/Magazine.java
  src/main/java/frc/robot/subsystems/Shooter.java
  vendordeps/Phoenix.json
Labels: enhancement, priority: high

#114 Update auto with new hood
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/ShooterRPM.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: Autonomous, priority: high

#115 add shop pipeline
  limelight pipelines/Shop_Targeting.vpr
Labels: enhancement, priority: high

#116 Game Day changes
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Magazine.java
Labels: bug

#119 Dripping Springs Day 2
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/MagazineRPM.java
  src/main/java/frc/robot/commands/ShooterRPM.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: bug, enhancement

#128 Turret Brake Mode
  src/main/java/frc/robot/subsystems/Turret.java
Labels: enhancement

#127 New hood rollers pid subsystem
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/ShooterRPM.java
  src/main/java/frc/robot/subsystems/ShooterRoller.java
Labels: enhancement

#130 Combine Shooter Subsystems
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/ShooterRPM.java
  src/main/java/frc/robot/subsystems/Shooter.java
  src/main/java/frc/robot/subsystems/ShooterRoller.java
Labels: bug

#131 Second magazine motor
  README.md
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/MagazineRPM.java
  src/main/java/frc/robot/subsystems/InnerMagazine.java
  src/main/java/frc/robot/subsystems/OuterMagazine.java
Labels: enhancement, Autonomous

#133 Brake mode only when not tracking
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/AlignTurret.java
  src/main/java/frc/robot/subsystems/Turret.java
Labels: bug, enhancement

#138 Updates from Austin Day 1
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/OutsideClimber.java
Labels: enhancement

#139 Austin day2
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P1_3B.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/AutoAlignTurret.java
  src/main/java/frc/robot/commands/ShooterRPM.java
  src/main/java/frc/robot/subsystems/InsideClimber.java
  src/main/java/frc/robot/subsystems/OutsideClimber.java
Labels: enhancement, Autonomous

#141 Austin Day 3 Updates
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P1_3B.java
  src/main/java/frc/robot/autos/P_2B.java
Labels: enhancement, Autonomous

#150 Update Path Planner Lib 2022.2.1
  .github/workflows/main.yml
  pathweaver/fields/2022-rapidreact/notes.md
  src/main/java/frc/robot/autos/LimelightAuto.java
  src/main/java/frc/robot/autos/P0.java
  src/main/java/frc/robot/autos/P1_3B.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/autos/TestNoZeroGyroAuto.java
  src/main/java/frc/robot/commands/AutoAlignTurret.java
  src/main/java/frc/robot/commands/IntakeOn.java
  src/main/java/frc/robot/commands/ZeroMotorsWaitCommand.java
  src/main/java/frc/robot/modules/AutoBase.java
  src/main/java/frc/robot/modules/swervedrive/SwerveModule.java
  src/main/java/frc/robot/subsystems/InnerMagazine.java
  src/main/java/frc/robot/subsystems/OuterMagazine.java
  src/main/java/frc/robot/subsystems/Swerve.java
  vendordeps/PathplannerLib.json
Labels: enhancement, Autonomous, priority: high

#144 Enable Driver mode when not aligning
  src/main/java/frc/robot/commands/AlignTurret.java
  src/main/java/frc/robot/modules/Vision.java
Labels: enhancement, priority: medium

#156 Replace Parallel command groups with methods
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P1_3B.java
  src/main/java/frc/robot/autos/P_2B.java
Labels: enhancement, Autonomous, priority: low

#151 Change the method to reset odometry
  src/main/java/frc/robot/autos/P0.java
  src/main/java/frc/robot/autos/P1_3B.java
  src/main/java/frc/robot/autos/P_2B.java
Labels: bug, Autonomous

#161 New inner mag PID values
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: priority: high

#160 Create command for auto rotation in place
  src/main/java/frc/robot/commands/TurnToAngle.java
  src/main/java/frc/robot/modules/AutoBase.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: enhancement, Autonomous
