Repository Frc5572/FRC2022, pull requests merged in 2022-04, with the labels that each got.

#167 Update limelight constants
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: enhancement

#164 Add code for Hood, includes new shooter PID values
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AlignHood.java
  src/main/java/frc/robot/commands/FeedShooter.java
  src/main/java/frc/robot/commands/InnerMagIntake.java
  src/main/java/frc/robot/commands/IntakeOn.java
  src/main/java/frc/robot/commands/MagazineRPM.java
  src/main/java/frc/robot/commands/PositionHood.java
  src/main/java/frc/robot/commands/ShooterRPM.java
  src/main/java/frc/robot/commands/WheelsIn.java
  src/main/java/frc/robot/subsystems/Hood.java
  src/main/java/frc/robot/subsystems/InnerMagazine.java
  src/main/java/frc/robot/subsystems/Intake.java
  src/main/java/frc/robot/subsystems/OuterMagazine.java
  src/main/java/frc/robot/subsystems/Shooter.java
  src/main/java/frc/robot/subsystems/Turret.java
Labels: enhancement, priority: high

#165 Led layouts
  simgui-ds.json
  simgui.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AlignHood.java
  src/main/java/frc/robot/commands/DefaultLEDs.java
  src/main/java/frc/robot/commands/PositionHood.java
  src/main/java/frc/robot/subsystems/Hood.java
  src/main/java/frc/robot/subsystems/InnerMagazine.java
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: enhancement, priority: low

#170 Add hardcoded shot for Safety location
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/ShooterRPM.java
Labels: enhancement, priority: medium

#179 Improve Auto Paths
  shuffleboard config/shuffleboard.json
  src/main/deploy/pathplanner/P1_3B_part2.path
  src/main/deploy/pathplanner/P1_3B_part3.path
  src/main/deploy/pathplanner/generatedJSON/P1_3B_part2.wpilib.json
  src/main/deploy/pathplanner/generatedJSON/P1_3B_part3.wpilib.json
  src/main/java/frc/lib/math/Conversions.java
  src/main/java/frc/robot/autos/P0.java
  src/main/java/frc/robot/autos/P1_3B.java
  src/main/java/frc/robot/autos/P1_5B.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/FeedShooter.java
  src/main/java/frc/robot/commands/TurnToAngle.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: Autonomous, priority: high

#182 DCMP Day 3
  shuffleboard config/shuffleboard.json
  src/main/deploy/pathplanner/P1_3B_part3.path
  src/main/deploy/pathplanner/P1_3B_part4.path
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P0.java
  src/main/java/frc/robot/autos/P1_3B.java
  src/main/java/frc/robot/autos/P1_5B.java
  src/main/java/frc/robot/autos/P_2B.java
  src/main/java/frc/robot/commands/FeedShooter.java
  src/main/java/frc/robot/commands/TurnToAngle.java
  src/main/java/frc/robot/subsystems/Turret.java
Labels: enhancement

#183 Add Position 2 - 4 Ball Auto
  src/main/deploy/pathplanner/P2_4B_part1.path
  src/main/deploy/pathplanner/P2_4B_part2.path
  src/main/deploy/pathplanner/P2_4B_part3.path
  src/main/deploy/pathplanner/generatedJSON/P2_4B_part1.wpilib.json
  src/main/deploy/pathplanner/generatedJSON/P2_4B_part2.wpilib.json
  src/main/deploy/pathplanner/generatedJSON/P2_4B_part3.wpilib.json
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/autos/P2_4B.java
Labels: enhancement, Autonomous, priority: low
